module Nfe
  module Resources
    class LegalEntityLookup < AbstractResource
      def get_basic_info: (untyped federal_tax_number, ?update_address: untyped, ?update_city_code: untyped) -> Nfe::LegalEntityBasicInfoResponse?
      def get_state_tax_info: (untyped state, untyped federal_tax_number) -> Nfe::LegalEntityStateTaxResponse?
      def get_state_tax_for_invoice: (untyped state, untyped federal_tax_number) -> Nfe::LegalEntityStateTaxForInvoiceResponse?
      def get_suggested_state_tax_for_invoice: (untyped state, untyped federal_tax_number) -> Nfe::LegalEntityStateTaxForInvoiceResponse?

      def api_family: () -> Symbol
      def api_version: () -> String
    end
  end
end
