module Nfe
  module Resources
    class NaturalPeople < AbstractResource
      ENVELOPE: String

      def api_family: () -> Symbol

      def list: (String company_id) -> Nfe::ListResponse
      def create: (String company_id, Hash[untyped, untyped] data) -> Nfe::NaturalPerson?
      def retrieve: (String company_id, String natural_person_id) -> Nfe::NaturalPerson?
      def update: (String company_id, String natural_person_id, Hash[untyped, untyped] data) -> Nfe::NaturalPerson?
      def delete: (String company_id, String natural_person_id) -> nil
      def create_batch: (String company_id, Array[Hash[untyped, untyped]] list) -> Array[Nfe::NaturalPerson?]
      def find_by_tax_number: (String company_id, String federal_tax_number) -> Nfe::NaturalPerson?

      private

      def json_headers: () -> Hash[String, String]
      def json_body: (untyped data) -> String
    end
  end
end
