module Nfe
  module Resources
    class NaturalPersonLookup < AbstractResource
      def get_status: (untyped federal_tax_number, untyped birth_date) -> Nfe::NaturalPersonStatusResponse?

      def api_family: () -> Symbol
      def api_version: () -> String
    end
  end
end
