module Nfe
  module Resources
    class StateTaxes < AbstractResource
      ENVELOPE: String
      LIST_ENVELOPE: String

      def api_family: () -> Symbol
      def api_version: () -> String

      def list: (String company_id, ?starting_after: untyped, ?ending_before: untyped, ?limit: untyped) -> Nfe::ListResponse
      def create: (String company_id, Hash[untyped, untyped] data) -> Nfe::NfeStateTax?
      def retrieve: (String company_id, String state_tax_id) -> Nfe::NfeStateTax?
      def update: (String company_id, String state_tax_id, Hash[untyped, untyped] data) -> Nfe::NfeStateTax?
      def delete: (String company_id, String state_tax_id) -> nil

      private

      def base_path: (String company_id) -> String
      def json_headers: () -> Hash[String, String]
    end
  end
end
