module Nfe
  module Resources
    class TaxCodes < AbstractResource
      def api_family: () -> Symbol
      def api_version: () -> String

      def list_operation_codes: (?page_index: Integer?, ?page_count: Integer?) -> Nfe::TaxCodePaginatedResponse?
      def list_acquisition_purposes: (?page_index: Integer?, ?page_count: Integer?) -> Nfe::TaxCodePaginatedResponse?
      def list_issuer_tax_profiles: (?page_index: Integer?, ?page_count: Integer?) -> Nfe::TaxCodePaginatedResponse?
      def list_recipient_tax_profiles: (?page_index: Integer?, ?page_count: Integer?) -> Nfe::TaxCodePaginatedResponse?

      private

      def list_tax_codes: (String path, Integer? page_index, Integer? page_count) -> Nfe::TaxCodePaginatedResponse?
    end
  end
end
