module Nfe
  class NaturalPerson < Data
    attr_reader id: String?
    attr_reader name: String?
    attr_reader federal_tax_number: String?
    attr_reader email: String?
    attr_reader address: untyped
    attr_reader created_on: String?
    attr_reader modified_on: String?

    def self.from_api: (Hash[untyped, untyped]? payload) -> Nfe::NaturalPerson?

    def self.new: (id: String?, name: String?, federal_tax_number: String?, email: String?, address: untyped, created_on: String?, modified_on: String?) -> instance

    def initialize: (id: String?, name: String?, federal_tax_number: String?, email: String?, address: untyped, created_on: String?, modified_on: String?) -> void
  end
end
